### ISSUE TITLE
Listen for UserMentioned and MessagePosted

### ISSUE THREAD

**Issue by FelixSFD** [Tunaki/chatexchange#2]
When I try to listen to the events `UserMentionedEvent` and `MessagePostedEvent`, I keep getting the following exception when the `UserMentionedEvent` is happening:

```
ERROR [Room:254] 2017-03-18 18:17:19,840 - Couldn't execute task
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: JsonNull
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: JsonNull
	at com.google.gson.JsonElement.getAsLong(JsonElement.java:230)
	at fr.tunaki.stackoverflow.chat.Room.lambda$send$11(Room.java:279)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 7 more
```

You can see my code in Guttenberg's branch `feature/81-global-alive-command`: https://github.com/SOBotics/Guttenberg/tree/feature/81-global-alive-command

SOBotics/Guttenberg#81

**Comment by Tunaki** [comment]
I remember seeing this exception occur also. It's very weird because it means that the WebSocket response from SE, of posting the chat message, [did not have an id](https://github.com/Tunaki/chatexchange/blob/b1c49bab537362de2a6b20171bac553776c716f4/src/main/java/fr/tunaki/stackoverflow/chat/Room.java#L279). I didn't investigate further because I couldn't reproduce (and understand) this reliably. Can you? It might be a bug within SE code itself...

A bit unclear what the method should return in such a case either.

**Comment by FelixSFD** [comment]
With Guttenberg, I can reproduce it. But it only happens, when I execute a command (whilst pinging Guttenberg) that is triggered by both events (although Guttenberg won't react to the `MessagePostedEvent`, when the message contains `@gut`. I'm already preventing him from doing this)

I'll try to find the exact line, where it happans

**Comment by FelixSFD** [comment]
nvm.. I've been stupid. I executed the command twice, because I didn't search for `@gut` correctly in the message.

**Comment by Tunaki** [comment]
There might really be a bug here (or a workaround some SE limitation). If you do have a reproducing scenario (even contrived), it'll be grateful.

**Comment by FelixSFD** [comment]
It happens, if you try to post the same message within a very short time period. This is not allowed and seems to result in that exception.
